### ISSUE TITLE
SD Card

### ISSUE THREAD

**Issue by P7R7M** [Georgia-Tech-Off-Road/GTORHardwareLibraries#4]

**Comment by Ian-Boraks** [comment]
Need to investigate changes in https://github.com/Georgia-Tech-Off-Road/DAQ/commit/001c6595b3a99ff7777ac1b02c840ca05d769416 from https://github.com/Georgia-Tech-Off-Road/DAQ/commit/3319bc7aa483086fa9c493b8422a80c9143a9f94

**Comment by Vishnav03** [comment]
SD card saves data, and file, /GTORDaata/DataAcquisition/StandaloneParsers/DataParser.py can be used to parse SD card, but the parsed data is inintelligible, need @randomzebra to check on that.

**Comment by randomzebra** [comment]
SD card write works correctly, bin file packets are intelligible. Data for sensors sometimes unintelligible because sensors data is interpreted as an integer or a float depending on a hardcoded sensorid match in the parser. Adding a sensor to be interpreted as a float fixes issue, but I will look into a general solution using the SensorID.py sensor dictionary type field. Closing this card and making a new one
